# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inference_server_pb2 as inference__server__pb2


class InferenceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Compute = channel.unary_unary(
        '/inference_server.Inference/Compute',
        request_serializer=inference__server__pb2.Input.SerializeToString,
        response_deserializer=inference__server__pb2.Output.FromString,
        )


class InferenceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Compute(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Compute': grpc.unary_unary_rpc_method_handler(
          servicer.Compute,
          request_deserializer=inference__server__pb2.Input.FromString,
          response_serializer=inference__server__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inference_server.Inference', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
